name: Deploy Shopify Theme

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Check theme
      run: npm run check
      
    - name: Deploy to development (on PR)
      if: github.event_name == 'pull_request'
      env:
        SHOPIFY_CLI_PARTNERS_TOKEN: ${{ secrets.SHOPIFY_CLI_PARTNERS_TOKEN }}
        SHOPIFY_STORE: ${{ secrets.SHOPIFY_STORE }}
      run: |
        npm run push -- --development
        
    - name: Deploy to production (on main)
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      env:
        SHOPIFY_CLI_PARTNERS_TOKEN: ${{ secrets.SHOPIFY_CLI_PARTNERS_TOKEN }}
        SHOPIFY_STORE: ${{ secrets.SHOPIFY_STORE }}
      run: |
        npm run deploy